#!/bin/bash

function cleanup() {
  kill $1
}

CARGO_TARGET_DIR="$(pwd)/target"
cargo build --release
ext=$?
if [[ $ext -ne 0 ]]; then
  exit $ext
fi
sudo setcap cap_net_admin=eip $CARGO_TARGET_DIR/release/tcp
$CARGO_TARGET_DIR/release/tcp &
pid=$!
trap "cleanup $pid" EXIT
sudo ip addr add 192.168.0.1/24 dev tun0
sudo ip link set up dev tun0
wait $pid
